#!/bin/bash

PID_FILE=/var/run/udhcpc.eth0.pid

if [ "$IFACE" == "eth0" ]; then

	ADDR=`ip addr show eth0|grep "inet "|head -n 1|awk '{print $2}'`

	if [ "$ADDR" != "" ]; then
		ip addr del $ADDR dev eth0
	fi

	route del default dev eth0

	if [ -e "$PID_FILE" ]; then
		PID=`cat $PID_FILE`
		kill -9 $PID
	fi
fi
