#!/bin/bash

if [ "$IFACE" == "eth0" ]; then

	# First try dhcp, the fallback in static IP
	udhcpc -n -i eth0 -h `hostname` -p /var/run/udhcpc.eth0.pid || ip addr add 192.168.1.200/24 dev eth0

fi

if [ "$IFACE" == "eth1" ]; then

	# First try dhcp, the fallback in static IP
	udhcpc -n -i eth1 -h `hostname` -p /var/run/udhcpc.eth1.pid || ip addr add 192.168.2.200/24 dev eth1

fi
